// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu1DANp5oJ14W8ffm2pyOQYNhCfPI3tM4',
    appId: '1:757575220829:web:251dec18f6a6e8d08b57b4',
    messagingSenderId: '757575220829',
    projectId: 'badge-system-a4af2',
    authDomain: 'badge-system-a4af2.firebaseapp.com',
    storageBucket: 'badge-system-a4af2.appspot.com',
    measurementId: 'G-S0XGTTNQ9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZi39hWi2PXKckZokSMDBlV5ztwIeZVVo',
    appId: '1:757575220829:android:0a6b6fcb69c3b5378b57b4',
    messagingSenderId: '757575220829',
    projectId: 'badge-system-a4af2',
    storageBucket: 'badge-system-a4af2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizLzbh1H0iNEuBAdWXWSPDZ_ppXJDFsE',
    appId: '1:757575220829:ios:5f76a944bb5da28d8b57b4',
    messagingSenderId: '757575220829',
    projectId: 'badge-system-a4af2',
    storageBucket: 'badge-system-a4af2.appspot.com',
    iosClientId: '757575220829-pomuj2k3e92msl32ql14g2saj5gth0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.badgeSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizLzbh1H0iNEuBAdWXWSPDZ_ppXJDFsE',
    appId: '1:757575220829:ios:5f76a944bb5da28d8b57b4',
    messagingSenderId: '757575220829',
    projectId: 'badge-system-a4af2',
    storageBucket: 'badge-system-a4af2.appspot.com',
    iosClientId: '757575220829-pomuj2k3e92msl32ql14g2saj5gth0kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.badgeSystem',
  );
}
